name: SessionAPI
description: "The library facilitates game containerization on a Minecraft server, enabling the creation of isolated environments within the game with separate logic and state."
version: '${project.version}'
main: pl.szelagi.SessionAPI
api-version: '1.21'
authors: [ Szelagi ]
depend:
  - FastAsyncWorldEdit

commands:
  #   Info
  craftcontainers:
    description: "Displays information about the SessionAPI library and its features."

  #   Session debug
  session-test:
    description: "Starts a test session for experimental or diagnostic purposes."
    permission: "sessionapi.debug"

  session-debug:
    description: "Toggles debugging messages on or off."
    permission: "sessionapi.debug"

  session-internal-test:
    description: "Command for running internal tests."
    permission: "sessionapi.test"

  # blueprint
  blueprint:
    description: "Manages the editor for creating and editing schematic structures."
    permission: "sessionapi.blueprint"

  # marker
  marker:
    description: "Manages saved coordinates within the Blueprint editor."
    permission: "sessionapi.blueprint"

  # container
  container:
    description: "Allows managing containers and the players in them."
    permission: "sessionapi.container"

permissions:
  sessionapi.debug:
    description: "Allows the user to start test sessions and toggle debug messages."
    default: op

  sessionapi.test:
    description: "Allows use of the integration test command"
    default: op

  sessionapi.blueprint:
    description: "Allows the user to manage blueprints"
    default: op

  sessionapi.container:
      description: "Allows the user to manage containers"
      default: op