name: SessionAPI
description: "SessionAPI Plugin"
version: '${project.version}'
main: pl.szelagi.SessionAPI
api-version: '1.20'
authors: [ Szelagi ]
commands:
  #   Board editor
  board-save:
    description: "editor board save"
  board-edit:
    description: "start board editor"
  board-exit:
    description: "exit board editor"
  board-list:
    description: "list of board saves"
  #   Session manage
  session-exit:
    description: "force session exit"
  session-add-player:
    description: "force session add player"
  session-remove-player:
    description: "force session remove player"
  session-join:
    description: "force join session"
  test-session:
    description: "start test session"
  show-debug:
    description: "show debug"
  hide-debug:
    description: "hide debug"
  tetest:
    description: "test"
  mobgame:
    description: "start mobgame"
  dual:
    description: "start dual"
  "randomgame":
    description: "start random"
  "uw":
    description: "UW"