name: CraftContainers
description: "The library facilitates game containerization on a Minecraft server, enabling the creation of isolated environments within the game with separate logic and state."
version: '${project.version}'
main: pl.szelagi.CraftContainers
api-version: '1.21'
authors: [ Szelagi ]
depend:
  - FastAsyncWorldEdit

commands:
  # Info
  craftcontainers:
    description: "Displays information about the CraftContainers framework and its features."

  # Session debug
  session-test:
    description: "Starts a test session for experimental or diagnostic purposes."
    permission: "craftcontainers.debug"

  session-debug:
    description: "Toggles debugging messages on or off."
    permission: "craftcontainers.debug"

  craftcontainers-e2e-test:
    description: "Command for running e2e tests."
    permission: "craftcontainers.test"

  # blueprint
  blueprint:
    description: "Manages the editor for creating and editing schematic structures."
    permission: "craftcontainers.blueprint"

  # marker
  marker:
    description: "Manages saved coordinates within the Blueprint editor."
    permission: "craftcontainers.blueprint"

  # container
  container:
    description: "Allows managing containers and the players in them."
    permission: "craftcontainers.container"

permissions:
  craftcontainers.debug:
    description: "Allows the user to start test sessions and toggle debug messages."
    default: op

  craftcontainers.test:
    description: "Allows use of the integration test command"
    default: op

  craftcontainers.blueprint:
    description: "Allows the user to manage blueprints"
    default: op

  craftcontainers.container:
      description: "Allows the user to manage containers"
      default: op